services:
type: web
name: workshop-todolist
runtime: docker
plan: free
healthCheckPath: /up
disk:
  name: rails-storage
  mountPath: /rails/storage
  sizeGB: 1
envVars:
key: b778492b27b163120a92253d69d3fe0a
sync: false